### ISSUE TITLE
Standardize arguments, set labels, set title, set colors, for plotting functions: limix.plot.plot_manhattan, limix.plot.qqplot, limix.plot.plot_kinship.

### ISSUE THREAD

**Issue by horta** [limix/limix#13]

**Comment by rbpisupati** [comment]
Can you also give the legend for different colors in limix.plot.qqplot? What are the three colors given in qqplot?

![qqplot for gwas](https://user-images.githubusercontent.com/11807889/32832483-edf17448-c9fb-11e7-9d76-2624cb79edf0.png)

**Comment by Horta** [comment]
I recommend giving limix development version a try: https://github.com/limix/limix/tree/develop

In the readme you will see a one-liner install for limix dev which should will solve those problems. And also I will be able to fix quickly issues that you might rise.

**Comment by rbpisupati** [comment]
So this is a bug in the qqplot function?

**Comment by Horta** [comment]
Yes and no. It is lack of documentation and not a nice interface. You can define the parameters `label` and `color` to achieve what you need: https://limix.readthedocs.io/en/stable/_modules/limix/plot/qqplot.html#qqplot
