### ISSUE TITLE
"python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by vafadarnejad** [limix/limix#26]
Hi

When I try `pip install limix`, I get the following error. 

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-YzCg7o/liknorm-py/`

Does anyone know how to solve it?

Best

**Comment by Horta** [comment]
That is weird. Would you please copy and paste here the results of

```
pip --version
python --version
which pip
which python
```

**Comment by vafadarnejad** [comment]
Dear Danilo Horta, 
Here is the information you wanted: 
`$ pip --version
pip 9.0.1 from /home/ehsan/.local/lib/python2.7/site-packages (python 2.7)
$ python --version
Python 2.7.12
$ which pip
/usr/local/bin/pip
$ which python
/usr/bin/python`

Thanks a lot.

**Comment by vafadarnejad** [comment]
Dear Danilo Horta,

Actually, I was able to install limix from local archive through the following command: 
`pip install ./downloads/limix-master.tar.gz` 
but I couldn't install it with `pip install limix`.
Here is the information you wanted:

`$ pip --version
pip 9.0.1 from /home/ehsan/.local/lib/python2.7/site-packages (python 2.7)
$ python --version
Python 2.7.12
$ which pip
/usr/local/bin/pip
$ which python
/usr/bin/python
`

Thanks a lot.

**Comment by Horta** [comment]
Limix depends on liknorm library: https://github.com/limix/liknorm I guess it might be the related to the problem... I'm happy that it worked out at the end though =)
