### ISSUE TITLE
Failed building liknorm.py

### ISSUE THREAD

**Issue by timflutre** [limix/limix#27]
Hello, I am giving a try to `limix`. My computer runs Ubuntu 16.04, and I executed the following command: `sudo pip install limix`.

First of all, I got this message:

    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable

This was fixed by doing `sudo apt install libffi-dev`.

Now, I am getting the following error:

    build/temp.linux-x86_64-2.7/liknorm._ffi.c:434:33: fatal error: liknorm/liknorm.h: No such file or directory

Any idea?
Best,
Tim

**Comment by Horta** [comment]
Hello,

Yes. You need liknorm library. If you are using conda you can do

`conda install -c conda-forge liknorm`

If you don't have conda, you can install via

```bash
git clone https://github.com/glimix/liknorm.git
cd liknorm
mkdir build
cd build
cmake ..
make
sudo make install
```

**Comment by timflutre** [comment]
Thanks, it worked. Maybe this could be specified for other users somewhere in the "Install" section?

**Comment by Horta** [comment]
You are right indeed. I'm adding that to the future 1.1.0 limix release. Thank you =)
