### ISSUE TITLE
Specify maximum number of threads

### ISSUE THREAD

**Issue by Bonder-MJ** [limix/limix#30]
Currently it is not possible to set the max number of threads. Which would be nice on LSF/PBS clusters

**Comment by Horta** [comment]
Going to fix that later. Meanwhile, you can do:

```bash
export MKL_NUM_THREADS=1
```

from shell. And from python,

```python
from multiprocessing.pool import ThreadPool
import dask
dask.set_options(pool=ThreadPool(1))
```
