### ISSUE TITLE
Error obtaining SE in VarDec

### ISSUE THREAD

**Issue by inti** [limix/limix#40]
When I try to get the SE for the variance component on the vardec analysis I get the following error

How can I get standard deviation or standard error for the variance component estimates?

```In [21]: >>> from numpy.random import RandomState
       : >>> from limix.vardec import VarianceDecomposition
       : >>> from numpy import dot, eye, ones
       : >>> from numpy import set_printoptions
       : >>> set_printoptions(4)
       : >>> random = RandomState(1)
       : >>>
       : >>> N = 100
       : >>> P = 3
       : >>>
       : >>> # generate data
       : >>> pheno = random.randn(N, P)
       : >>> W = random.randn(N, 10)
       : >>> kinship = dot(W, W.T) / float(10)
       : >>> kinship+= 1e-4*eye(N)
       : >>> F1 = ones((N, 1))
       : >>> A1 = eye(P)
       : >>> F2 = random.randn(N, 2)
       : >>> A2 = ones((1, P))
       : >>>
       : >>> vc = VarianceDecomposition(pheno)
       : >>> vc.addFixedEffect(F1, A1)
       : >>> vc.addFixedEffect(F2, A2)
       : >>> vc.addRandomEffect(K=kinship)
       : >>> vc.addRandomEffect(is_noise=True)
       : >>> conv = vc.optimize()
       :
       :

In [22]: vc.getVarianceComps()
Out[22]:
array([[ 0.0097,  1.0029],
       [ 0.0562,  0.8284],
       [ 0.0096,  0.8147]])
In [23]: vc.getVarianceCompStdErrors()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-a360ee5f6476> in <module>()
----> 1 vc.getVarianceCompStdErrors()

/Users/intipedroso/DATA/app/uBiome/statgen/miniconda2/envs/production/lib/python2.7/site-packages/limix/vardec/vardec.pyc in getVarianceCompStdErrors(self, univariance)
    697         for term_i in range(self.n_randEffs):
    698             # RV[:,term_i] = self.getTraitCovarStdErrors(term_i).diagonal()
--> 699             RV[:, term_i] = self.getTraitCovarStdErrors(term_i)
    700         var = self.getVarianceComps()
    701         if univariance:

/Users/intipedroso/DATA/app/uBiome/statgen/miniconda2/envs/production/lib/python2.7/site-packages/limix/vardec/vardec.pyc in getTraitCovarStdErrors(self, term_i)
    662         """
    663         assert self.init, 'GP not initialised'
--> 664         assert self.fast is False, 'Not supported for fast implementation'
    665
    666         if self.P == 1:

AttributeError: 'VarianceDecomposition' object has no attribute 'fast'```

**Comment by Horta** [comment]
Sorry for this. We are working hard on a new version with a more uniform interface and documentation examples and tutorials automatically tested. @fpcasale Do you have a quick fix for this until we have a new release?

**Comment by fpcasale** [comment]
Unfortunately, no quick fix in this case. We are working on this and it will be fixed in the new release. Apologies for the inconvenience.

**Comment by inti** [comment]
@fpcasale do you have a timeframe for the next release? Thanks in advance

**Comment by inti** [comment]
@fpcasale any updates on this issue? thanks in advance

**Comment by avinuela** [comment]
Hi, 
We are having the same issue while trying to get SE. Has it been any progress on fixing this? I am not sure I even understand why the error happens. 

Thanks, 
Ana.

**Comment by horta** [comment]
Hi all, I've just implemented variance decomposition in our future release. Please refer to https://github.com/limix/limix/tree/2.0.0 for how to proceed with the installation. The documentation for variance decomposition can be found here: https://limix.readthedocs.io/en/2.0.0/tutorials/vardec.html

Really sorry for the long delay. I will be able to answer quickly on the 2.0.0 development version. So please don't give on posting here if you find any issue.

**Comment by horta** [comment]
Hi, you mean jointly multi-trait decomposition? Not yet I'm afraid :/ I can implement variance standard errors quickly for the single-trait, which I will do it today and report it back here!

**Comment by horta** [comment]
Please, refer to limix 3.0.0.
