### ISSUE TITLE
How to fit a mixed model with several kinship matrix 

### ISSUE THREAD

**Issue by Minglc** [limix/limix#45]
I want to use limix to fit a mixed model with several random effects terms, and just for one trait and one variant at a time, How would i implement this?

**Comment by Minglc** [comment]
I want to use limix to fit a mixed model with several kinship matrix, and just for one trait and one variant at a time, How would i implement this?

**Comment by horta** [comment]
Hi @Minglc , please have a look at https://github.com/limix/limix/issues/46
