### ISSUE TITLE
Log Likelihood-ratio error

### ISSUE THREAD

**Issue by Minglc** [limix/limix#49]
I want to use the variance decomposition functions to fit a linear model with two random effects, so I make the following codes to get the Log Likelihood-ratio. I am  confused about the Log Likelihood-ratio , why the  Log Likelihood-ratio in the null mode is much bigger.
```
In [584]: %paste

        vc1 = limix.vardec.VarianceDecomposition(phenos_df)
        vc1.addFixedEffect(F=exp_df,A=np.ones((1, 1)))
        vc1.addRandomEffect(K=Kg)
        vc1.addRandomEffect(K=KG)
        vc1.addRandomEffect(is_noise=True)
        vc1.optimize()
        vc1_lml = vc1.getLML()

## -- End pasted text --

In [585]: %paste

        vc3 = limix.vardec.VarianceDecomposition(phenos_df)
        vc3.addFixedEffect()
        vc3.addRandomEffect(K=Kg)
        vc3.addRandomEffect(K=KG)
        vc3.addRandomEffect(is_noise=True)
        vc3.optimize()
        vc3_lml = vc3.getLML()

## -- End pasted text --

In [586]: vc1_lml
Out[586]: 348.5713181228375

In [587]: vc3_lml
Out[587]: 353.9244572792586
```

**Comment by horta** [comment]
Hi @Minglc , is it single trait? If so, could you try a development limix version https://github.com/limix/limix/tree/2.0.0 ?

Doc: https://limix.readthedocs.io/en/2.0.0/tutorials/vardec.html

**Comment by Minglc** [comment]
ok, thanks for your reply！
