### ISSUE TITLE
unclear documentation for multi trait analysis

### ISSUE THREAD

**Issue by tavareshugo** [limix/limix#59]
Hi,

Apologies if this is the wrong place to raise this issue, which is related with the documentation found in the [limix tutorials repo](https://github.com/limix/limix-tutorials). 

I am trying to follow the tutorial on [multi-trait analysis](https://nbviewer.jupyter.org/github/limix/limix-tutorials/blob/master/LMM_multitrait/LMM_multitrait_example.ipynb), but I think the readers are not up-to-date with current version of limix. 

I have previously been successfull at running a script based on that tutorial, using `limix v0.7.12`, but things do not seem to work for current versions. For example, the step using `limix.io.genotype_reader.genotype_reader_tables` throws the error: `'function' object has no attribute 'genotype_reader_tables'`.

Can you provide with some clues on how to construct the `QTLData` object with the current version? Or if there is an alternative way to run the three multi-trait tests ("any effect", "common effect" and "interaction effect"). 

My genotype data are in PLINK format and my phenotypes in CSV. (I can convert these to HDF5 using `limix_convert` if necessary).

Many thanks,
hugo

**Comment by horta** [comment]
Hi @tavareshugo , I would install a newer version (in development):

```
bash <(curl -fsSL https://raw.githubusercontent.com/limix/limix/develop/install)
```

and follow the document in here: http://limix.readthedocs.io/en/develop/

Let me know how it goes...

**Comment by tavareshugo** [comment]
Dear @horta,

Thanks for your suggestion. I have installed the dev version. I will try to figure things out from the documentation. 

A question about getting data ready. If I understand, one has to do some "manual" data handling beforehand to read the genotypes (`limix.io.read_plink()`), read the phenotypes (`pandas.read_csv()`), and then intersect these two datasets to retain only common individuals (i.e. with both genotypes and phenotypes). In the previous version there was a `QTLData` object that did some of this work for us and ensured we got genotypes + phenotypes together. Is that not the case anymore?

Further to that, my understanding was that the GxE tests can be done with `limix.qtl.iscan()`?

**Comment by horta** [comment]
Hi @tavareshugo ,

Sorry for the delay. QTLData was the case in limix 1.x.x I believe. I had started working on that for limix 2.0.0-dev but haven't finished it. I will work on that today and get something ready. If I understood correctly, you are mainly interested in reading two type of files for now: BED and CSV files. Is that right?

And yes, GxE is done fix `limix.qtl.iscan` if you can describe the environment for all samples by a vector.

**Comment by tavareshugo** [comment]
Hi @horta,

To be fair, I meanwhile ran my old script on an environment where I still had limix 0.7.12 installed, which solved my problem for now (not ideal, but...). 

In any case, I'd be happy to test if you implement something new. 

Indeed, my genotypes are in PLINK format (with files `.fam`, `.bed` and `.bim`) and phenotypes in a plain `.csv` file. I managed to read them with `limix.io.read_plink()` and read the trait data with `pandas.read_csv()`. Then I was trying to cross-reference these two and gave up (mostly because I'm an R person and get frustrated at how slow I am with python :slightly_smiling_face:)

I can describe the environment by a vector, that's not a problem. But then I guess LIMIX will need to be happy that individual IDs are duplicated, because the same genotype occurs in multiple environments (these are inbred Arabidopsis lines, so we have clonal replicates in each environment/treatment).

In other words, my phenotype file might be something like:

```
ID     ENV    TRAIT_VALUE
1       A         10
1       B         20
2       A         11
2       B         15
3       A         8
3       B         8
```

So, if I use `TRAIT_VALUE` as the `y` vector and `ENV` as the `inter` vector, then the genotype (`G`) and relatedness (`K`) matrices will need to have two entries for each of these IDs, right?

Alternatively, one can shape the data in "wide" format, which is how it seemed to work with previous versions, such as the one in the [tutorial](https://nbviewer.jupyter.org/github/limix/limix-tutorials/blob/master/LMM_multitrait/LMM_multitrait_example.ipynb):

```
ID    TRAIT_ENVA    TRAIT_ENVB
1         10            20
2         11            15
3         8             8
```

In this case the genotype and relatedness matrices do not need to have duplicated entries for each ID. I guess it all depends on how the model is currently implemented under the hood.

**Comment by horta** [comment]
Thanks for the interest =)
*I'm on your case yet.

When you say clonal replicates, you mean that phenotypes (or covariates) will have samples with same IDs but the genotype itself has unique IDs? Because that case is covered on limix 2.0.0-dev, which is the on I'm working on right now.

**Comment by tavareshugo** [comment]
hi @horta ,

Thanks for looking into this. 
If I got your notation right, yes, the test for a GxE interaction is comparing the full model with a model where `alpha_{0,1} = 0`.

But there's more tests one might want to do:

* Test for overall genetic effect: compare full model with model where `alpha_{0} = alpha_{0, 1} = 0`
* Test for genetic effect only (accounting for environment): compare a model with no interaction (i.e. `alpha_{0, 1} = 0`) with a non-genetic model (i.e. `alpha_{0} = alpha_{0, 1} = 0`)

Does this make sense?

**Comment by horta** [comment]
Please, refer to limix 3.0.0.
