### ISSUE TITLE
python 2 construct in limix-tutorials/data/__init__.py

### ISSUE THREAD

**Issue by parsifal9** [limix/limix#66]
Hi all,
In working through the limix-tutorials in LMM_singletrait/LMM_example.ipynb
I get an error message (shown below). A web search seems to show that this is a Python 3
message about a Python 2 construct.

```sys.path.append('./..')
import data as tutorial_data
file_name = tutorial_data.get_file('arab107')

Traceback (most recent call last):
  File "/home/dun280/local/anaconda3/envs/Limix/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-f7ca326eca59>", line 2, in <module>
    import data as tutorial_data
  File "./../data/__init__.py", line 40
    print "file not found, downloading from %s" % study['url']
                                                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("file not found, downloading from %s" % study['url'])?
```
My installation procedure was
```conda create --name Limix python
conda activate Limix
conda install -c conda-forge limix
conda install jupyter
cd limix-tutorials
jupyter notebook index.ipynb 
```
Have I done somthing wrong?

**Comment by horta** [comment]
Hi @parsifal9 ,

Please, have a look at https://github.com/limix/limix/tree/2.0.0 . We are soon to release limix 2.0.0 with those problem fixed. In that same page, at Install section, you can see how to install it.

Also, you can see at https://limix.readthedocs.io/en/2.0.0/ the up-to-date documentation.
