### ISSUE TITLE
Missing documentation for limix 2.0

### ISSUE THREAD

**Issue by avinuela** [limix/limix#73]
Any chance you will be releasing documentation (tutorials) for limix 2.0 any time soon? Everything is different in the new version and there is not way to understand how to run anything compare to the stable version 1. 
Thanks, 
Ana.

**Comment by horta** [comment]
Hi @avinuela , we just release version 2.0.0: https://pypi.org/project/limix/
Documentation: http://limix.readthedocs.io/

We will be making new releases in the following days and weeks as we really hasnt finish everything. Feedbacks are always welcome =)

**Comment by abrown25** [comment]
Thanks for getting back to us, we realise this is a work in progress and things may be yet to settle down.
We're trying to convert scripts from limix 1 to limix 2 and not really sure we're on the right lines. Would you mind letting us know if we're getting this right:

vc = limix.vardec.VarianceDecomposition(data) # limix 1
is equivalent to:
vc = limix.glmm.GLMMComposer(len(data)) # limix 2
vc.y = data

vc.addFixedEffect() # (add linear intercept)
is:
vc.fixed_effects.append_offset()

and once we've fitted the model,
vc.getVarianceComps(univariance = False)[0]
is equivalent to:
vc.covariance_matrices[0]

Hope this makes sense, thanks again for your help.
Andrew

**Comment by horta** [comment]
Working on that!

**Comment by horta** [comment]
Hi @abrown25 , I know that is very late but, please, consider using the development version. Documentation regarding variance decomposition: https://limix.readthedocs.io/en/develop/vardec.html

How to install it: ``pip install git+https://github.com/limix/limix.git@develop``

**Comment by horta** [comment]
Please, refer to limix 3.0.0.
