### ISSUE TITLE
new conda recipes

### ISSUE THREAD

**Issue by quattro** [limix/limix#85]
Hi,

I wanted to first say thank you for creating such useful python packages for the GWAS and statgen community. They have simplified and enabled so much more for my day-to-day research.  

The recent limix(-\*) group of packages have been updated to 2.0* versions in pypi but the conda-forge recipes still list the 1.0* versions. Is it possible to update the feedstock for limix and limix-core to their latest?

I started to make a fork for the feedstock but `conda skeleton pypi limix` does a poor job of grabbing the dependencies. If there is a straightforward solution I'm happy to contribute to the fork and make a pull req.

**Comment by phue** [comment]
Hi,
I'm also a big fan of limix and I would really like to have an updated conda package.

As far as I can tell, limix-plot, limix-lmm and struct-lmm are new dependencies in limix 2.x and need to be packaged first.

I opened a work-in-progress PR here: https://github.com/conda-forge/limix-feedstock/pull/16

Would be great if we could join efforts there.

**Comment by horta** [comment]
Hi guys, thanks a lot for the interest. I have been working on the dependecies of linux in the last two weeks in order to remove one or two of new limix dependencies. So i would wait at least another week before we can work on the conda package.

**Comment by phue** [comment]
Great news!

I suppose limix-plot, limix-lmm and struct-lmm still need to be packaged? If so, I would be happy to help with that in the meantime.

**Comment by quattro** [comment]
Sounds great.

**Comment by horta** [comment]
Hi @phue , create a conda package for limix-plot would be great. I want to replace limix-lmm by glimix-core, which is already in conda-forge. Struct-lmm will require a new release before it can go to conda-forge channel. To create a conda package on the conda-forge, you start from here: https://github.com/conda-forge/staged-recipes

**Comment by phue** [comment]
> Hi @phue , create a conda package for limix-plot would be great. I want to replace limix-lmm by glimix-core, which is already in conda-forge. Struct-lmm will require a new release before it can go to conda-forge channel. To create a conda package on the conda-forge, you start from here: https://github.com/conda-forge/staged-recipes

:+1: 
Here's an open PR, I just need to figure out why tests are failing.
https://github.com/conda-forge/staged-recipes/pull/7889

**Comment by horta** [comment]
We now have limix 3.x released under conda as well =) https://anaconda.org/conda-forge/limix

**Comment by kauralasoo** [comment]
I'm having trouble installing the latest version of limix from conda on macOS.

Running ' conda install -c conda-forge limix' wants to install the following packages:
limix-1.0.18               |           py36_0         791 KB  conda-forge
limix-core-1.0.2           |             py_3          50 KB  conda-forge
limix-legacy-0.8.12        |   py36hf8a1672_4         1.7 MB  conda-forge

When I try to specify version 3.0.2, I get the following error:
(limix) Kaurs-MacBook-Pro-2:~ alasoo$ conda install -c conda-forge limix=3.0.2

Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - limix=3.0.2 -> pandas-plink[version='>=1.2.30']

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/r/osx-64
  - https://conda.anaconda.org/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

What am I doing wrong?

Best,
Kaur
