### ISSUE TITLE
Unclear documentation: st_iscan

### ISSUE THREAD

**Issue by ivanov-v-v** [limix/limix#88]
First and foremost, thank you for this wonderful tool. I decided to use it for QTL mapping part of my project and had a hard time understanding the documentation page for **st_iscan**. I am new to GLMMs, so I would be grateful if you could elaborate on some points.

![image](https://user-images.githubusercontent.com/8493747/55232655-47099500-5237-11e9-9f2e-af1e9b179200.png)
_What are **E0** and **E1**?_ How do they differ from each other? Which entities do they encode? For example, I want to incorporate information about the physical interactions between genes in the model (in the form of an incidence matrix). Is there a way to do it in this notation?  

_Moreover, how does **st_scan** handle missing values?_ If I have a genotypes matrix made up of 0s, 1s and NaNs, how should I impute the latter? From my experience, other packages require replacing NaNs with some value that mustn't be otherwise present in the data, like -1 or 2. Is this the case with **limix**? I tried to find something on NaN-handling policy on the documentation website but didn't succeed. Are there some restrictions on the input values, by the way? Am I correct in saying, that one should encode the variants with 0s and 1s when working with a cross of two stable strains (yeast data)? 

Generally speaking, it would be great to see some examples with real data in the documentation, as those given seem too simplistic to cover the issues arising during actual QTL mapping. I found two examples [here, in limix-tutorials repository](https://github.com/limix/limix-tutorials) but couldn't find links to those on the documentation website.
Thank you for your time and understanding!

**Comment by horta** [comment]
Thanks a lot for the feedback, @ivanov-v-v . We are working on the 3.0.0 release. I believe we have a better documentation for the interaction tests when you have multiple-traits.  It is not as fast as the single-trait, but you can already test it simply passing a single trait.

In the readme here you can see how to install the 3.0.0 development release: https://github.com/limix/limix/tree/develop

Here is the concerning function that might help you: https://github.com/limix/limix/blob/develop/limix/qtl/_mt_scan.py

You  can also see the documentation from your python terminal:

```python
import limix
help(limix.qtl.mt_scan)
```

**Comment by ivanov-v-v** [comment]
Thanks for your reply, @horta! I am looking forward to the new release, I will definitely check it out.
Nevertheless, I am still curious about **st_iscan**. I read the documentation for **mt_scan**, but it only added to the overall confusion. I really want to use limix in my project, it would be very kind of you if you could explain to me how to use it properly.

![image](https://user-images.githubusercontent.com/8493747/55875681-4c9f9d00-5b9e-11e9-920e-3e2aa5a629f3.png)
The main questions remain: _what are E0 and E1_, how are they different from each other? Why exactly do we need to specify two matrices? Here is what's written in the concluding paragraph of the same section:
![image](https://user-images.githubusercontent.com/8493747/55875895-e0716900-5b9e-11e9-8da2-46c2b081d574.png)
But what is alpha? It's doesn't occur in the formula above. Next, E0 isn't a _column-vector_, is it? It must be a matrix of the same shape as G. Maybe, it's a conventional notation, but I really can't the definitions from the examples given.

I deploy my project on the university computer cluster, thereby speed is definitely not the problem. As I mentioned before, I want to carry out QTL mapping that takes into account the interactions between genes of interest (like in [GFLASSO](https://www.datacamp.com/community/tutorials/gflasso-R)), but I can't figure out how to do it in this notation. If there is a way to run the same experiments using mt_scan instead of st_iscan, I would be glad to learn about it.

Best regards.

**Comment by horta** [comment]
Hi @ivanov-v-v , sorry for the confusion. I have tried to clarify it.

Here is the general explanation: https://limix.readthedocs.io/en/develop/qtl.html#single-trait-with-interaction
Here is the function documentation: https://limix.readthedocs.io/en/develop/api/limix.qtl.iscan.html#limix.qtl.iscan

Ideally, it would be possible to understand only by read the documentation. If it still unclear, let me know. I plan to have a release by tomorrow, so every feedback is welcome and will be implemented quickly.

**Comment by horta** [comment]
Please, refer to limix 3.0.0.
