### ISSUE TITLE
Example: glucose condition Fails

### ISSUE THREAD

**Issue by AmmarMalik93** [limix/limix#89]
Hi, 
I am trying to implement the glucose condition example posted here [https://limix.readthedocs.io/en/latest/vardec.html](url)

But I am getting the following error
`File "<ipython-input-74-652c448d4e19>", line 1, in <module>
    runfile('/home/ammar/Documents/limix_try', wdir='/home/ammar/Documents')`
` File "/home/ammar/anaconda3/envs/limixenv/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)`
`File "/home/ammar/anaconda3/envs/limixenv/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)`
`  File "/home/ammar/Documents/limix_try", line 64, in <module>
    glmm.fixed_effects.append_offset()`
`File "/home/ammar/anaconda3/envs/limixenv/lib/python3.7/site-packages/limix/glmm/_composer.py", line 247, in append_offset
    mean = OffsetMean()`
`TypeError: __init__() missing 1 required positional argument: 'n'`

Any help in this regard would be appreciated.

**Comment by horta** [comment]
Hi @AmmarMalik93 , please, have a look at our development version documentation: https://limix.readthedocs.io/en/develop/vardec.html

You can install it via ``pip install git+https://github.com/limix/limix.git@develop``

**Comment by AmmarMalik93** [comment]
Thank you @horta I will check this one out. Just one more question if you can answer please. Is it possible to get the loglikelihood value for the obtained covariance matrix? Actually we are working on a similar problem, so we want to compare our method with yours. We thought may be comparing the loglikelihood values for the obtained covariance matrix would be a good idea. But I am not sure how to compute these values for LIMIX or PANAMA.

**Comment by horta** [comment]
Hi @AmmarMalik93 , you can checkout how https://limix.readthedocs.io/en/develop/model.html
We are now export the inference methods we use to implement limix. It sounds like that is what you want. Example:

```python
from numpy import array
from numpy_sugar.linalg import economic_qs_linear
from limix.model.lmm import LMM

X = array([[1, 2], [3, -1]], float)
QS = economic_qs_linear(X)
covariates = array([[1], [1]])
y = array([-1, 2], float)
lmm = LMM(y, covariates, QS)
lmm.fix("delta")
lmm.fix("scale")
lmm.delta = 0.5
lmm.scale = 1
lmm.fit(verbose=False)
print("%.3f" % lmm.lml())

lmm.unfix("delta")
lmm.fit(verbose=False)
print("%.3f" % lmm.lml())
```

**Comment by horta** [comment]
Should be all fine on limix 3.0.0
