### ISSUE TITLE
memory leak on iteration?

### ISSUE THREAD

**Issue by lukemn** [limix/limix#90]
Hi @horta, 
I'm using limix for some simulations and seeing a linear increase in memory consumption when I iterate. Specifically, the combination of a qtl scan `r = scan(G, y, "normal", verbose=False)` then assigning the stats `o = r.stats` should reproduce it using your example code, modified here in [leak.txt](https://github.com/limix/limix/files/3097909/leak.txt).

I'm using
python 3.6.5/3.7.0
limix 3.0.dev4
numpy 1.16.2
pandas 0.24.2

Here's the top five files:lines from `tracemalloc` after a few iterations on a bigger data set, where total memory use went from ~2G to ~20G in the space of a few minutes.

> /home/lmn3/.local/lib/python3.7/site-packages/limix/qtl/_result/_st_factory.py:25: size=800 MiB (+733 MiB), count=14296070 (+13104729), average=59 B
/home/lmn3/.local/lib/python3.7/site-packages/limix/qtl/_result/_st_factory.py:35: size=727 MiB (+667 MiB), count=4765260 (+4368155), average=160 B
/home/lmn3/.local/lib/python3.7/site-packages/numpy/core/numeric.py:538: size=591 MiB (+542 MiB), count=9531313 (+8737009), average=65 B
/home/lmn3/.local/lib/python3.7/site-packages/limix/qtl/_scan.py:309: size=582 MiB (+533 MiB), count=7146596 (+6551032), average=85 B
/home/lmn3/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py:1861: size=255 MiB (+233 MiB), count=200 (+176), average=1305 KiB

Putting these calls within functions, and (re)initializing the objects each loop doesn't seem to do anything. Any idea how I can get around this?

Thanks

**Comment by horta** [comment]
Hi @lukemn , how large is your dataset? I run that leak.txt script here until the end and I got as last results:

```
[ Top 10 (it 10000 vs 0 ]
/anaconda3/lib/python3.7/site-packages/numpy/lib/twodim_base.py:0: size=764 MiB (+764 MiB), count=20001 (+19999), average=39.1 KiB
/anaconda3/lib/python3.7/site-packages/glimix_core-3.1.5-py3.7.egg/glimix_core/lmm/_lmm.py:0: size=36.7 MiB (+36.7 MiB), count=160105 (+159984), average=241 B
/Users/horta/code/limix/limix/qtl/_result/_st_factory.py:0: size=29.8 MiB (+29.8 MiB), count=340003 (+339966), average=92 B
/anaconda3/lib/python3.7/site-packages/numpy/core/numeric.py:0: size=26.7 MiB (+26.6 MiB), count=428340 (+428264), average=65 B
/anaconda3/lib/python3.7/site-packages/glimix_core-3.1.5-py3.7.egg/glimix_core/lmm/_lmm_scan.py:0: size=24.9 MiB (+24.9 MiB), count=310127 (+309975), average=84 B
/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py:0: size=22.1 MiB (+22.0 MiB), count=383685 (+383526), average=60 B
/anaconda3/lib/python3.7/site-packages/pandas/core/internals/blocks.py:0: size=16.2 MiB (+16.2 MiB), count=300105 (+300048), average=57 B
/anaconda3/lib/python3.7/site-packages/xarray/core/dataarray.py:0: size=13.4 MiB (+13.4 MiB), count=195164 (+194787), average=72 B
/anaconda3/lib/python3.7/site-packages/xarray/core/indexing.py:0: size=8645 KiB (+8596 KiB), count=20295 (+20059), average=436 B
/anaconda3/lib/python3.7/site-packages/xarray/core/dataset.py:0: size=8286 KiB (+8216 KiB), count=93667 (+93265), average=91 B
```

Looking at memory usage I didnt see a significant increase in memory usage.

If you comment ``o = r.stats`` out the problem vaishes? If so I would suspect either pandas dataframe as causing large usage of memory or a bug ``from functools import lru_cache``. but I would bet the first case.

**Comment by horta** [comment]
You might want to force garbage collection: https://docs.python.org/3/library/gc.html
If that solves the problem, it might not be a leaking problem...

**Comment by horta** [comment]
I suspect that it might just be that we are saving quite a lot of information in those scans. Numpy/pandas/etc. might reason that keeping a large amount of memory allocated it will be best for speeding up. How many candidates and samples do you have?

**Comment by lukemn** [comment]
Yeah, looping on the test data doesn't grow much, but it does grow. My data
are not massive ... ~1000 individuals, 250k SNPs ... but big enough to
cause problems when doing a lot of iterations.

And yes, just doing the scan is fine, so it's definitely something about
assignment from the scan object. My first (OK, second) thought was pandas
too.

I tried forcing garbage collection, doesn't help unfortunately,

Thanks.

**Comment by horta** [comment]
I have an idea. Will be able to test in 2 hours from now, then I report here back.

**Comment by horta** [comment]
I have been running

```python
#!/usr/bin/env python3

from numpy import ones, stack
from numpy.random import RandomState
from pandas import DataFrame
from limix.qtl import scan
import tracemalloc

random = RandomState(1)

# sample size
n = 1000
# genetic variants
m = 250000
G = random.randn(n, m)
# sampling the phenotype
beta = random.randn(m)
eps = random.randn(n)
y = G @ beta + eps

snaps = []
tracemalloc.start()
for i in range(1, 10001):
    r = scan(G, y, "normal", verbose=False)
    o = r.stats
    if i == 1 or i % 1000 == 0:
        snapshot = tracemalloc.take_snapshot()
        snaps.append(snapshot)
        if i > 1:
            print()
            top_stats = snapshot.compare_to(snaps[0], "filename")
            print("[ Top 10 (it {} vs 0 ]".format(i))
            for stat in top_stats[:10]:
                print(stat)
```

for about 15 min now. There is no significant memory usage so far.

Are you using conda? If so, you might want to do ``conda update --all`` to see if it solves the problem. Also, we have limix 3.0.0 released: ``pip install limix -U``.

**Comment by lukemn** [comment]
Stayed low, I assume? Weird. Running that code at similar scale (n=1000,
m=100000) does it for me on a Linux cluster (~2 - >24Gb in 20 iterations,
about 15 mins) and my laptop (spills to swap around 10 iterations).

CentOS (freshly updated conda env, limix 3.0.0):

[ Top 10 (it 20 vs 0 ]

/home/lmn3/.local/lib/python3.7/site-packages/limix/qtl/_result/_st_factory.py:0:
size=1496 MiB (+1421 MiB), count=19999976 (+18999971), average=78 B

/home/lmn3/.local/lib/python3.7/site-packages/numpy/core/numeric.py:0:
size=664 MiB (+631 MiB), count=12000650 (+11400582), average=58 B

/home/lmn3/.local/lib/python3.7/site-packages/limix/qtl/_scan.py:0:
size=625 MiB (+594 MiB), count=7998452 (+7598484), average=82 B

/home/lmn3/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py:0:
size=214 MiB (+203 MiB), count=924 (+768), average=237 KiB

/home/lmn3/.local/lib/python3.7/site-packages/limix/qtl/_result/_st_result.py:0:
size=208 MiB (+197 MiB), count=4000048 (+3799990), average=54 B

/home/lmn3/.local/lib/python3.7/site-packages/numpy/lib/twodim_base.py:0:
size=153 MiB (+145 MiB), count=81 (+77), average=1929 KiB

/home/lmn3/.local/lib/python3.7/site-packages/pandas/core/internals/blocks.py:0:
size=67.2 MiB (+59.5 MiB), count=671 (+611), average=103 KiB

/home/lmn3/.local/lib/python3.7/site-packages/numpy/core/shape_base.py:0:
size=61.0 MiB (+58.0 MiB), count=3999945 (+3799943), average=16 B

/home/lmn3/.local/lib/python3.7/site-packages/glimix_core/lmm/_lmm_scan.py:0:
size=31.1 MiB (+29.5 MiB), count=935 (+768), average=34.0 KiB

/share/apps/anaconda3/5.3.1/lib/python3.7/tracemalloc.py:0: size=269 KiB
(+269 KiB), count=4792 (+4792), average=57 B


Mac (virtualenv, limix 3.0.dev4):

[ Top 10 (it 20 vs 0 ]

/Users/noble/py3.6/lib/python3.6/site-packages/limix/qtl/_result/_st_factory.py:0:
size=1496 MiB (+1421 MiB), count=19999978 (+18999973), average=78 B

/Users/noble/py3.6/lib/python3.6/site-packages/numpy/core/numeric.py:0:
size=985 MiB (+935 MiB), count=14000438 (+13300385), average=74 B

/Users/noble/py3.6/lib/python3.6/site-packages/limix/qtl/_scan.py:0:
size=305 MiB (+290 MiB), count=5998888 (+5698901), average=53 B

/Users/noble/py3.6/lib/python3.6/site-packages/pandas/core/internals/managers.py:0:
size=214 MiB (+203 MiB), count=936 (+786), average=234 KiB

/Users/noble/py3.6/lib/python3.6/site-packages/limix/qtl/_result/_st_result.py:0:
size=208 MiB (+197 MiB), count=4000057 (+3799996), average=54 B

/Users/noble/py3.6/lib/python3.6/site-packages/numpy/lib/twodim_base.py:0:
size=153 MiB (+145 MiB), count=81 (+77), average=1929 KiB

/Users/noble/py3.6/lib/python3.6/site-packages/pandas/core/internals/blocks.py:0:
size=67.2 MiB (+59.5 MiB), count=667 (+608), average=103 KiB

/Users/noble/py3.6/lib/python3.6/site-packages/numpy/core/shape_base.py:0:
size=61.0 MiB (+58.0 MiB), count=3999944 (+3799942), average=16 B

/Users/noble/py3.6/lib/python3.6/site-packages/glimix_core/lmm/_lmm_scan.py:0:
size=31.1 MiB (+29.5 MiB), count=941 (+771), average=33.8 KiB

/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tracemalloc.py:0:
size=226 KiB (+226 KiB), count=3996 (+3996), average=58 B

**Comment by horta** [comment]
Try to update pandas/dask/xarray packages. Also you can have limix 3.0.1.

**Comment by lukemn** [comment]
Everything's shiny, no change.
limix 3.0.1
pandas 0.24.2
dask 1.2.0
xarray 0.12.1

**Comment by horta** [comment]
I might have encoutered that problem in my experiments just now. It doesnt seem to be memory leak but simply too much memory usage. I will see here what I can do.

**Comment by horta** [comment]
Hi @lukemn , I've optimized memory usage for when sorting the results out. It is not perfect but it allowed me to scan 5 millions of SNPs using 20GB max. You can try it out using: ``pip install git+https://github.com/limix/limix.git@develop``
