### ISSUE TITLE
Installing the latest version of limix on macOS

### ISSUE THREAD

**Issue by kauralasoo** [limix/limix#91]
I'm having trouble installing the latest version of limix from conda on macOS.

Running ' conda install -c conda-forge limix' wants to install the following packages:
limix-1.0.18 | py36_0 791 KB conda-forge
limix-core-1.0.2 | py_3 50 KB conda-forge
limix-legacy-0.8.12 | py36hf8a1672_4 1.7 MB conda-forge

When I try to specify version 3.0.2, I get the following error:
(limix) Kaurs-MacBook-Pro-2:~ alasoo$ conda install -c conda-forge limix=3.0.2

Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

limix=3.0.2 -> pandas-plink[version='>=1.2.30']
Current channels:

https://conda.anaconda.org/conda-forge/osx-64
https://conda.anaconda.org/conda-forge/noarch
https://conda.anaconda.org/bioconda/osx-64
https://conda.anaconda.org/bioconda/noarch
https://repo.anaconda.com/pkgs/main/osx-64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/free/osx-64
https://repo.anaconda.com/pkgs/free/noarch
https://repo.anaconda.com/pkgs/r/osx-64
https://repo.anaconda.com/pkgs/r/noarch
https://conda.anaconda.org/r/osx-64
https://conda.anaconda.org/r/noarch
To search for alternate channels that may provide the conda package you're
looking for, navigate to

https://anaconda.org
and use the search bar at the top of the page.

What am I doing wrong?

Best,
Kaur

**Comment by horta** [comment]
Thanks Kaur. For some reason pandas-plink didnt get updated on conda-forge for macos. I just built it again. Should be working now!
