### ISSUE TITLE
Estimating the kinship matrix from human genotype data

### ISSUE THREAD

**Issue by kauralasoo** [limix/limix#93]
Hello!

We are following the Limix eQTL tutorial (https://github.com/limix/limix-tutorials/blob/master/eQTL.ipynb) and trying to adapt it to human data. What is the recommended way to estimate the kinship matrix from human genotype data? We currently have a VCF file consisting of ~450 individuals and 9 million imputed genetic variants. 

Should we convert the VCF file to PLINK format and use the limix.io.plink.read function to import the file into Python? Should we perform LD pruning before we try to estimate kinship? Are there any recommended parameters for that? How to manage the memory requirements, because even after LD pruning the genotype matrix can be quite large.

Best,
Kaur

**Comment by horta** [comment]
Hi @kauralasoo , would you mind posting that question in the Limix support forum? https://forum.limix.io

You would be the first one =) I just started hosting it to have a place for limix questions

**Comment by kauralasoo** [comment]
Ok, done:
https://forum.limix.io/topic/4/estimating-the-kinship-matrix-from-human-genotype-data
