### ISSUE TITLE
A few typos in the doc on QTL

### ISSUE THREAD

**Issue by Romain-B** [limix/limix#94]
I was looking through the doc of your package (very comprehensive, by the way) and spotted a couple of typos : 
These are on the following page (https://limix.readthedocs.io/en/latest/qtl.html)
 - At the end of the **Introduction**, "an array of effect sizes 𝛃 " -- I think you mean "𝛂"
 - In **Statistical test**, "𝓗₀ is defined by **\<placing a\>** constraint **\<on\>** one or more parameters ~~if~~ **\<of\>** the alternative model 𝓗₁.", &nbsp;  as well as  &nbsp; "The likelihood ratio statistics is give **\<n\>** by".

**Comment by horta** [comment]
Thanks a lot, @Romain-B , I have fixed those issue. I will be available in the next release =)
