### ISSUE TITLE
K matrix as covariance matrix

### ISSUE THREAD

**Issue by picla** [limix/limix#95]
Is there a way to correct for populations structure by adding the kinship matrix as a covariate to the model without doing the eigendecomposition?
As I understand from the source, limix.qtl._scan is doing this decomposition by default without the possibility to disable it.

**Comment by horta** [comment]
The eigen-decomposition is an implementation artifact: it doesnt have to do with population structure correction per si. Just pass `K=None` to the `scan` function so it won't have any kinship matrix.

**Comment by horta** [comment]
And compute the principal components of your kinship matrix and add them to the covariates.

**Comment by picla** [comment]
But I actually don’t want to use PCs for population structure correction.
I want to use the full sample x sample kinship matrix.
If I get it right, the eigendecomposition is summarising the kinship matrix, similarly as to what PCs do.
However, comparing the single trait GWAS in LIMIX with PyGWAS (using the full kinship matrix as correction for population structure), the limix results give lots of highly significant peaks around the centromeres in, which in my opinion suggest incomplete correction for population structure.
What I ultimately want to do is run single trait GWAS correcting for population structure and with one locus fixed as covariate.
Therefore I would need to be able to add the kinship matrix (K), without eigendecomposition, to the model together with a certain covariate (M).



On 30.07.2019, at 18:10, Danilo Horta <notifications@github.com<mailto:notifications@github.com>> wrote:


And compute the principal components of your kinship matrix and add them to the covariates.

**Comment by horta** [comment]
The [https://en.wikipedia.org/wiki/Eigendecomposition_of_a_matrix](eigen-decomposition) preserve the entire structure of the matrix you provide: nothing is lost. The problem you might be facing is not due that decomposition.

Try difference settings: without providing kinship matrix; providing kinship matrix; not providing kinship matrix but providing the first PCAs of that kinship matrix as covariates; permute the kinship matrix rows-and-columns jointly to see how the results change.

**Comment by picla** [comment]
Hi Danilo,
Seems like there was a flaw in my own code, which was messing with the order of the accessions in the phenotype array.
Results look way more similar to pyGWAS now.
Sorry for bothering.
